<?php

/**
 * Proxy Class for \PenumbraExamples\One\Entities\Tag auto-generated by Penumbra.
 *                  --DO NOT MODIFY--
 */

namespace PenumbraExamples\One\Proxies;

use Penumbra\Drivers\Base\Object\Properties\Proxies\IProxy as IProxy;
use Penumbra\Drivers\Base\Object\Properties\Proxies\EntityProxyFunctionality as ProxyFunctionality;

class PenumbraExamples_One_Entities_Tag_Proxy extends \PenumbraExamples\One\Entities\Tag implements IProxy {
    use ProxyFunctionality;
    
    public function __construct() {
        return call_user_func_array([$this, '__ConstructProxy'], func_get_args());
    }

    
}

?>