<?php

/**
 * Proxy Class for \Storm\Tests\Integration\ObjectRelationalModels\Blog\Entities\Author auto-generated by Storm.
 *                  --DO NOT MODIFY--
 */

namespace Storm\Tests\Integration\ObjectRelationalModels\Blog\Proxies;

use Storm\Drivers\Base\Object\Properties\Proxies\IProxy as IProxy;
use Storm\Drivers\Base\Object\Properties\Proxies\EntityProxyFunctionality as ProxyFunctionality;

class Storm\Tests\Integration\ObjectRelationalModels\Blog_One_Entities_Author_Proxy extends \Storm\Tests\Integration\ObjectRelationalModels\Blog\Entities\Author implements IProxy {
    use ProxyFunctionality;
    
    public function __construct() {
        return call_user_func_array([$this, '__ConstructProxy'], func_get_args());
    }

    
}

?>