<?php

/**
 * Proxy Class for \StormTests\One\Entities\Blog auto-generated by STORM.
 *                  --DO NOT MODIFY--
 */

namespace StormTests\One\Mapping\Proxies;

use Storm\Drivers\Base\Mapping\Proxy\IEntityProxy as IProxy;
use Storm\Drivers\Base\Mapping\Proxy\EntityProxyFunctionality as ProxyFunctionality;

class StormTests_One_Entities_Blog__Proxy extends \StormTests\One\Entities\Blog implements IProxy {
    use ProxyFunctionality;
    
    public function __construct() {
        return call_user_func_array([$this, '__ConstructProxy'], func_get_args());
    }

       
    public function HelloWorld ($Hi) {
        $this->__Load();
        return parent::HelloWorld($Hi);
    }
}

?>